In [1]:
import pyscf
import pyscf.tools
from pyscf import lo, gto


from orbitalpartitioning import *


molecule = """
 Fe 1.67785607 0.00052233 0.06475932
 O 0.00000000 0.00000000 -0.47099074
 Fe -1.67785607 -0.00052233 0.06475932
 Cl 1.87002704 -1.09796437 1.99091682
 Cl 2.93244917 -0.98210488 -1.47467288
 Cl 2.37160936 2.07954091 -0.50446591
 Cl -1.87002704 1.09796437 1.99091682
 Cl -2.93244917 0.98210488 -1.47467288
 Cl -2.37160936 -2.07954091 -0.50446591
 """

pymol = pyscf.gto.Mole(
        atom    =   molecule,
        symmetry=   False,
        spin    =   10, # number of unpaired electrons
        charge  =   -2)
pymol.build()

mf = pyscf.scf.ROHF(pymol)
mf.verbose = 4
mf.conv_tol = 1e-8
mf.conv_tol_grad = 1e-5
mf.chkfile = "scf.fchk"
mf.init_guess = "minao"
mf.run()
##################################################################




******** <class 'pyscf.scf.rohf.ROHF'> ********
method = ROHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-08
SCF conv_tol_grad = 1e-05
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = scf.fchk
max_memory 4000 MB (current use 0 MB)
num. doubly occ = 77  num. singly occ = 10


/Users/arnab/arnab/workspace/.venv/lib/python3.9/site-packages/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


init E= -5289.63018546547
  HOMO = 0.473246078347936  LUMO = 0.476436886667608
cycle= 1 E= -5289.15069324983  delta_E= 0.479  |g|= 2.84  |ddm|= 8.23
  HOMO = -0.000303795913088585  LUMO = 0.0865952448133479
cycle= 2 E= -5276.15095510045  delta_E=   13  |g|= 4.14  |ddm|= 9.58

WARN: HOMO 0.91237260160557 >= LUMO 0.129031757301241

cycle= 3 E= -5291.20851605663  delta_E= -15.1  |g|= 2.39  |ddm|= 9.69
  HOMO = 0.192121528469596  LUMO = 0.454224553216504
cycle= 4 E= -5297.24364203003  delta_E= -6.04  |g|= 1.78  |ddm|= 8.96
  HOMO = 0.193863066010525  LUMO = 0.42795476467271
cycle= 5 E= -5298.42555810989  delta_E= -1.18  |g|= 1.11  |ddm|= 2.29
  HOMO = 0.210765039775199  LUMO = 0.462271180548417
cycle= 6 E= -5298.85407691721  delta_E= -0.429  |g|= 0.769  |ddm|= 0.815
  HOMO = 0.274855837559083  LUMO = 0.489189175123916
cycle= 7 E= -5299.01857415372  delta_E= -0.164  |g|= 0.531  |ddm|= 0.544
  HOMO = 0.36836069561283  LUMO = 0.519055272060728
cycle= 8 E= -5299.07246980464  delta_E= -0.0539  

# ROHF/6-31G*

In [2]:
pymol.basis = "6-31g*"
pymol.build()
mf = pyscf.scf.ROHF(pymol)
mf.verbose = 4
mf.conv_tol = 1e-8
mf.conv_tol_grad = 1e-5
mf.chkfile = "scf.fchk"
mf.init_guess = "chkfile"
mf.run()
##################################################################



******** <class 'pyscf.scf.rohf.ROHF'> ********
method = ROHF
initial guess = chkfile
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-08
SCF conv_tol_grad = 1e-05
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = scf.fchk
max_memory 4000 MB (current use 0 MB)
num. doubly occ = 77  num. singly occ = 10
init E= -5355.01675380936
  HOMO = 0.118460129710996  LUMO = 0.348131329113568
cycle= 1 E= -5356.63553764889  delta_E= -1.62  |g|= 0.699  |ddm|= 2.87
  HOMO = -0.105049941073753  LUMO = 0.332215864709712
cycle= 2 E= -5355.38925263732  delta_E= 1.25  |g|= 1.83  |ddm|= 1.84
  HOMO = 0.0817638485561647  LUMO = 0.343204640393557
cycle= 3 E= -5356.6896456804  delta_E= -1.3  |g|= 0.445  |ddm|= 1.66
  HOMO = 0.00718713220009578  LUMO = 0.333756751381668
cycle= 4 E= -5356.67058202987  delta_E= 0.0191  |g|= 0.339  |ddm|= 0.776
  HOMO = 0.012506899826872  LUMO = 0.33312851

In [3]:
# Print out orbital energies
for i,ei in enumerate(mf.mo_energy):
    print(" Orbital %3i:  %12.8f" %(i, ei))


 Orbital   0:  -261.36190561
 Orbital   1:  -261.36190384
 Orbital   2:  -104.54215702
 Orbital   3:  -104.54215047
 Orbital   4:  -104.51896425
 Orbital   5:  -104.51896226
 Orbital   6:  -104.51789814
 Orbital   7:  -104.51789217
 Orbital   8:  -31.95808049
 Orbital   9:  -31.95807935
 Orbital  10:  -27.43860820
 Orbital  11:  -27.43860820
 Orbital  12:  -27.43771381
 Orbital  13:  -27.43771324
 Orbital  14:  -27.43672164
 Orbital  15:  -27.43672011
 Orbital  16:  -20.25097694
 Orbital  17:  -10.28405433
 Orbital  18:  -10.28405047
 Orbital  19:  -10.26041519
 Orbital  20:  -10.26041104
 Orbital  21:  -10.26027609
 Orbital  22:  -10.26027442
 Orbital  23:   -7.75203085
 Orbital  24:   -7.75202983
 Orbital  25:   -7.75010756
 Orbital  26:   -7.75010519
 Orbital  27:   -7.75003649
 Orbital  28:   -7.75003342
 Orbital  29:   -7.72839357
 Orbital  30:   -7.72839289
 Orbital  31:   -7.72823147
 Orbital  32:   -7.72823091
 Orbital  33:   -7.72642336
 Orbital  34:   -7.72642170
 Orbital  35

In [4]:
ncore = 41

#
#   Get data
F = mf.get_fock()
C = mf.mo_coeff
S = mf.get_ovlp()
Cdocc = mf.mo_coeff[:,mf.mo_occ==2]
Csing = mf.mo_coeff[:,mf.mo_occ==1]
Cvirt = mf.mo_coeff[:,mf.mo_occ==0]

# Get core
# Ccore = Cdocc[:,0:ncore]
# Cdocc = Cdocc[:,ncore:]

# ncore = Ccore.shape[1]
ndocc = Cdocc.shape[1]
nsing = Csing.shape[1]
nvirt = Cvirt.shape[1]

print(" Norbs = %6i ncore = %6i ndocc = %6i nsing = %6i nvirt = %6i"%(Cdocc.shape[0], ncore, ndocc, nsing, nvirt))
assert( ndocc + nsing + nvirt == F.shape[1])

 Norbs =    190 ncore =     41 ndocc =     77 nsing =     10 nvirt =    103


In [5]:
# Find AO's corresponding to atoms
full = []
frags = [[] for i in range(9)]

for ao_idx,ao in enumerate(mf.mol.ao_labels(fmt=False)):
    if ao[0] == 0:
        if ao[2] in ("3d",):
            frags[0].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 1:
        if ao[2] in ("2p","3p"):
            frags[1].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 2:
        if ao[2] in ("3d",):
            frags[2].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 3:
        if ao[2] in ("3p","4p"):
            frags[3].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 4:
        if ao[2] in ("3p","4p"):
            frags[4].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 5:
        if ao[2] in ("3p","4p"):
            frags[5].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 6:
        if ao[2] in ("3p","4p"):
            frags[6].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 7:
        if ao[2] in ("3p","4p"):
            frags[7].append(ao_idx)
            full.append(ao_idx)
    elif ao[0] == 8:
        if ao[2] in ("3p","4p"):
            frags[8].append(ao_idx)
            full.append(ao_idx)


print(frags)



#
#   Get full active space
(Oact, Sact, Vact), (Oenv, Cerr, Venv) = svd_subspace_partitioning_nonorth((Cdocc, Csing, Cvirt), full, S)
assert(Cerr.shape[1] == 0)
print(" Oenv.shape = ", Oenv.shape)
print(" Venv.shape = ", Venv.shape)
print(" Oact.shape = ", Oact.shape) 
print(" Vact.shape = ", Vact.shape)
print(" Sact.shape = ", Sact.shape)


[[17, 18, 19, 20, 21], [37, 38, 39, 40, 41, 42], [65, 66, 67, 68, 69], [89, 90, 91, 92, 93, 94], [107, 108, 109, 110, 111, 112], [125, 126, 127, 128, 129, 130], [143, 144, 145, 146, 147, 148], [161, 162, 163, 164, 165, 166], [179, 180, 181, 182, 183, 184]]
 In svd_subspace_partitioning_nonorth
 Partition  190 orbitals into a total of   52 orbitals
            Index   Sing. Val. Space       
                0   0.99980424            0*
                1   0.99974693            0*
                2   0.99973593            0*
                3   0.99962775            0*
                4   0.99910252            0*
                5   0.99908449            0*
                6   0.99826430            2*
                7   0.99816235            0*
                8   0.99768217            0*
                9   0.99757388            0*
               10   0.99721383            0*
               11   0.99719504            0*
               12   0.99652877            0*
               13   0

In [6]:

#   Split active space into fragments
init_fspace = []
clusters = []
Cfrags = []

orb_index = 1


for fi,f in enumerate(frags):
    print()
    print(" Fragment: ", f)
    (Of, Sf, Vf), (_, _, _) = svd_subspace_partitioning_nonorth((Oact, Sact, Vact), f, S)

    Cfrags.append(np.hstack((Of, Sf, Vf)))
    ndocc_f = Of.shape[1]
    init_fspace.append((ndocc_f+Sf.shape[1], ndocc_f))
    nmof = Of.shape[1] + Sf.shape[1] + Vf.shape[1]
    clusters.append(list(range(orb_index, orb_index+nmof)))
    orb_index += nmof


# Orthogonalize Fragment orbitals
Cfrags = sym_ortho(Cfrags, S)

# Pseudo canonicalize fragments
Cfrags = canonicalize(Cfrags, F)


Cact = np.hstack(Cfrags)

print(" sing vals of active space: ", np.linalg.svd(Cact.T @ S @ Cact)[1])
# Write Molden files for visualization
pyscf.tools.molden.from_mo(mf.mol, "Cact.molden", Cact)
# for i in range(len(frags)):
#     di = Cfrags[i] @ Cfrags[i].T
#     pyscf.tools.cubegen.density(mf.mol, 'fragden_{:02d}.cube'.format(i+1), di)






 Fragment:  [17, 18, 19, 20, 21]
 In svd_subspace_partitioning_nonorth
 Partition   52 orbitals into a total of    5 orbitals
            Index   Sing. Val. Space       
                0   0.92578269            1*
                1   0.92360783            1*
                2   0.91561521            1*
                3   0.90711254            1*
                4   0.89646121            1*
                5   0.25101380            0
                6   0.21805118            0
                7   0.19201813            0
                8   0.14087439            0
                9   0.12312585            0
               10   0.07410908            2
               11   0.07263456            2
               12   0.06200839            2
               13   0.05730357            2
               14   0.05113620            2
  SVD active space has the following dimensions:
  Orbital Block    Environment         Active
              0             21              0
              1        

In [7]:
# Now add in the frozen core and virtuals
ncore = Oenv.shape[1]
init_fspace.insert(0, (ncore, ncore))
init_fspace.append((0,0))
for ci in range(len(clusters)):
    for cij in range(len(clusters[ci])):
        clusters[ci][cij] += ncore-1
clusters.insert(0,[i for i in range(ncore)])
clusters.append([i for i in range(ncore+Cact.shape[1], ncore+Cact.shape[1]+Venv.shape[1])])

# Now increase index by one since we will paste into Julia
for ci in range(len(clusters)):
    for cij in range(len(clusters[ci])):
        clusters[ci][cij] += 1

Cact = np.hstack((Oenv, Cact, Venv))
print("init_fspace = ", init_fspace)
print("clusters    = ", clusters)

init_fspace =  [(56, 56), (5, 0), (3, 3), (5, 0), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (0, 0)]
clusters    =  [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], [57, 58, 59, 60, 61], [62, 63, 64, 65, 66, 67], [68, 69, 70, 71, 72], [73, 74, 75, 76, 77, 78], [79, 80, 81, 82, 83, 84], [85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96], [97, 98, 99, 100, 101, 102], [103, 104, 105, 106, 107, 108], [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]]


# Make integrals

In [8]:
#   Make integrals
#
# d1_embed = 2 * Ccore @ Ccore.T
d1_embed=np.zeros((190,190))
h0 = pyscf.gto.mole.energy_nuc(mf.mol)
h  = pyscf.scf.hf.get_hcore(mf.mol)
j, k = pyscf.scf.hf.get_jk(mf.mol, d1_embed, hermi=1)

h0 += np.trace(d1_embed @ ( h + .5*j - .25*k))

h = Cact.T @ h @ Cact;
j = Cact.T @ j @ Cact;
k = Cact.T @ k @ Cact;
nact = h.shape[0]

h2 = pyscf.ao2mo.kernel(pymol, Cact, aosym="s4", compact=False)
h2.shape = (nact, nact, nact, nact)
# The use of d1_embed only really makes sense if it has zero electrons in the
# active space. Let's warn the user if that's not true

S = pymol.intor("int1e_ovlp_sph")
n_act = np.trace(S @ d1_embed @ S @ Cact @ Cact.T)
if abs(n_act) > 1e-8 == False:
    print(n_act)
    error(" I found embedded electrons in the active space?!")

h1 = h + j - .5*k;

np.save("ints_h0", h0)
np.save("ints_h1", h1)
np.save("ints_h2", h2)
np.save("mo_coeffs", Cact)
np.save("overlap_mat", S)

Pa = mf.make_rdm1()[0]
Pb = mf.make_rdm1()[1]
np.save("Pa", Cact.T @ S @ Pa @ S @ Cact)
np.save("Pb", Cact.T @ S @ Pb @ S @ Cact)

In [9]:
j = 1
clusters_out = []
for ci in clusters:
    c = []
    for i in range(j,j+len(ci)):
        c.append(i)
        j+=1
    clusters_out.append(c)


print("clusters = ", clusters_out)
print("init_fspace = ", init_fspace)

clusters =  [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], [57, 58, 59, 60, 61], [62, 63, 64, 65, 66, 67], [68, 69, 70, 71, 72], [73, 74, 75, 76, 77, 78], [79, 80, 81, 82, 83, 84], [85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96], [97, 98, 99, 100, 101, 102], [103, 104, 105, 106, 107, 108], [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]]
init_fspace =  [(56, 56), (5, 0), (3, 3), (5, 0), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (3, 3), (0, 0)]


In [18]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(0, 56)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_docc.cube', di)

array([[[9.36939617e-09, 1.27656811e-08, 1.75263045e-08, ...,
         7.05005268e-09, 6.01714298e-09, 5.12210555e-09],
        [1.23194327e-08, 1.69279359e-08, 2.33938217e-08, ...,
         8.47454644e-09, 7.23097135e-09, 6.15427198e-09],
        [1.60168893e-08, 2.21569611e-08, 3.07752091e-08, ...,
         1.01351093e-08, 8.64573418e-09, 7.35719784e-09],
        ...,
        [4.87006694e-08, 6.33574733e-08, 8.16267522e-08, ...,
         9.30994802e-09, 7.81106629e-09, 6.51945633e-09],
        [3.09933551e-08, 4.01456157e-08, 5.15463922e-08, ...,
         7.14860919e-09, 6.02399518e-09, 5.05200381e-09],
        [1.97874994e-08, 2.54639353e-08, 3.25246622e-08, ...,
         5.54017672e-09, 4.68711325e-09, 3.94766671e-09]],

       [[1.46258323e-08, 2.04547923e-08, 2.86545333e-08, ...,
         8.36062563e-09, 7.12855734e-09, 6.06370293e-09],
        [1.94596600e-08, 2.73804708e-08, 3.85221644e-08, ...,
         1.00506505e-08, 8.56657660e-09, 7.28518967e-09],
        [2.55368399e-08, 

In [19]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

for i in range(56, 61):
    di = Ccmf[:,[i]] @  Ccmf[:,[i]].T
    pyscf.tools.cubegen.density(pymol, 'fragden_fe1_{}.cube'.format(i+1), di)

In [20]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

for i in range(61, 67):
    di = Ccmf[:,[i]] @  Ccmf[:,[i]].T
    pyscf.tools.cubegen.density(pymol, 'fragden_oxygen_{}.cube'.format(i+1), di)

In [21]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

for i in range(67, 72):
    di = Ccmf[:,[i]] @  Ccmf[:,[i]].T
    pyscf.tools.cubegen.density(pymol, 'fragden_fe2_{}.cube'.format(i+1), di)


In [22]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(72, 78)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl1.cube', di)

array([[[2.71751444e-08, 2.88419755e-08, 3.02150387e-08, ...,
         4.32348896e-09, 3.71529100e-09, 3.18506804e-09],
        [3.18859292e-08, 3.37182961e-08, 3.51788916e-08, ...,
         5.06151954e-09, 4.35651492e-09, 3.74089911e-09],
        [3.73028379e-08, 3.93173846e-08, 4.08703623e-08, ...,
         5.89535683e-09, 5.08292509e-09, 4.37224324e-09],
        ...,
        [2.28023453e-08, 2.56551599e-08, 2.87149363e-08, ...,
         2.14835768e-08, 1.83599482e-08, 1.56235406e-08],
        [1.84409547e-08, 2.07144326e-08, 2.31478161e-08, ...,
         1.75438500e-08, 1.50312326e-08, 1.28237020e-08],
        [1.49080471e-08, 1.67267217e-08, 1.86708949e-08, ...,
         1.43036106e-08, 1.22830583e-08, 1.05031167e-08]],

       [[3.03997850e-08, 3.18658326e-08, 3.29108102e-08, ...,
         5.36654250e-09, 4.61307130e-09, 3.95568053e-09],
        [3.55342673e-08, 3.70867041e-08, 3.81166483e-08, ...,
         6.28864283e-09, 5.41430369e-09, 4.65021452e-09],
        [4.14288295e-08, 

In [23]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(78, 84)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl2.cube', di)

array([[[5.08178462e-09, 6.10114924e-09, 7.33050417e-09, ...,
         2.75644286e-09, 2.36885495e-09, 2.02777219e-09],
        [6.03765760e-09, 7.24979130e-09, 8.71254414e-09, ...,
         3.30304767e-09, 2.83974325e-09, 2.43180876e-09],
        [7.11778878e-09, 8.54459630e-09, 1.02665679e-08, ...,
         3.93959183e-09, 3.38839776e-09, 2.90280399e-09],
        ...,
        [5.73153212e-09, 6.59128281e-09, 7.55997151e-09, ...,
         5.15567529e-09, 4.47867548e-09, 3.87915439e-09],
        [4.96982846e-09, 5.71567919e-09, 6.55466996e-09, ...,
         4.54294454e-09, 3.93916246e-09, 3.40513166e-09],
        [4.28537664e-09, 4.93041925e-09, 5.65528415e-09, ...,
         3.96851077e-09, 3.43507682e-09, 2.96382913e-09]],

       [[6.39093057e-09, 7.72655587e-09, 9.35122242e-09, ...,
         3.27855676e-09, 2.81783066e-09, 2.41235538e-09],
        [7.59148594e-09, 9.18044095e-09, 1.11146052e-08, ...,
         3.92367125e-09, 3.37375861e-09, 2.88950649e-09],
        [8.94386815e-09, 

In [24]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(84, 90)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl3.cube', di)

array([[[3.18248284e-08, 3.42773636e-08, 3.65603010e-08, ...,
         2.43222110e-08, 2.10754916e-08, 1.81867591e-08],
        [3.72501485e-08, 4.00185599e-08, 4.25680968e-08, ...,
         2.94386559e-08, 2.55213607e-08, 2.20334882e-08],
        [4.34615590e-08, 4.65874424e-08, 4.94388657e-08, ...,
         3.54746256e-08, 3.07687684e-08, 2.65758147e-08],
        ...,
        [3.47157660e-08, 3.90736305e-08, 4.38262029e-08, ...,
         8.63660954e-08, 7.46177014e-08, 6.42050838e-08],
        [3.08781045e-08, 3.49175204e-08, 3.93509366e-08, ...,
         7.31811657e-08, 6.31901191e-08, 5.43400824e-08],
        [2.71877795e-08, 3.08721255e-08, 3.49375899e-08, ...,
         6.16368970e-08, 5.31936557e-08, 4.57186426e-08]],

       [[3.57304777e-08, 3.80776499e-08, 4.01349051e-08, ...,
         2.87033510e-08, 2.48816720e-08, 2.14793051e-08],
        [4.16683536e-08, 4.42695522e-08, 4.65090469e-08, ...,
         3.47137955e-08, 3.01074588e-08, 2.60033720e-08],
        [4.84532575e-08, 

In [25]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(90, 96)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl4.cube', di)

array([[[1.34720147e-07, 1.61782269e-07, 1.94571589e-07, ...,
         4.23052024e-08, 3.72476049e-08, 3.26382333e-08],
        [1.63543821e-07, 1.96575784e-07, 2.36643247e-07, ...,
         5.17254330e-08, 4.55477639e-08, 3.99158851e-08],
        [1.96907828e-07, 2.36791249e-07, 2.85196436e-07, ...,
         6.29287228e-08, 5.54198707e-08, 4.85725487e-08],
        ...,
        [1.46960027e-07, 1.70038492e-07, 1.94764869e-07, ...,
         3.07673215e-07, 2.41752706e-07, 1.87716231e-07],
        [1.07086205e-07, 1.23532534e-07, 1.41178868e-07, ...,
         2.03197975e-07, 1.60440734e-07, 1.25375970e-07],
        [7.82645654e-08, 8.99925118e-08, 1.02589523e-07, ...,
         1.34523180e-07, 1.06994556e-07, 8.43802681e-08]],

       [[1.69438151e-07, 2.05445384e-07, 2.49601999e-07, ...,
         5.12109322e-08, 4.51128446e-08, 3.95487630e-08],
        [2.05945534e-07, 2.49980571e-07, 3.04045882e-07, ...,
         6.26171940e-08, 5.51681714e-08, 4.83694038e-08],
        [2.48150897e-07, 

In [26]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(96, 102)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl5.cube', di)

array([[[4.93700647e-08, 5.44297490e-08, 5.92710572e-08, ...,
         6.45962387e-08, 5.52698844e-08, 4.70677003e-08],
        [5.90690662e-08, 6.52986738e-08, 7.13380710e-08, ...,
         7.64101661e-08, 6.53961451e-08, 5.57053798e-08],
        [7.06598346e-08, 7.84026325e-08, 8.60369508e-08, ...,
         8.99093684e-08, 7.69698639e-08, 6.55802332e-08],
        ...,
        [1.25450517e-05, 1.59561664e-05, 2.00166980e-05, ...,
         4.44363192e-08, 3.78008947e-08, 3.20258116e-08],
        [8.06184986e-06, 1.02629121e-05, 1.28860291e-05, ...,
         3.77892823e-08, 3.21295182e-08, 2.72070127e-08],
        [5.08868990e-06, 6.48308936e-06, 8.14665467e-06, ...,
         3.19908765e-08, 2.71863138e-08, 2.30102407e-08]],

       [[5.66862449e-08, 6.19466206e-08, 6.67758207e-08, ...,
         7.75644841e-08, 6.63981818e-08, 5.65665423e-08],
        [6.80270388e-08, 7.45981879e-08, 8.07530779e-08, ...,
         9.17256323e-08, 7.85440455e-08, 6.69322159e-08],
        [8.16957941e-08, 

In [27]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(102, 108)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_cl6.cube', di)

array([[[1.16268964e-06, 1.71160592e-06, 2.49421583e-06, ...,
         6.61510219e-08, 5.54565105e-08, 4.64481363e-08],
        [1.50289001e-06, 2.21592461e-06, 3.23269492e-06, ...,
         7.92870195e-08, 6.64326556e-08, 5.56190124e-08],
        [1.91402619e-06, 2.82574858e-06, 4.12592975e-06, ...,
         9.45084006e-08, 7.91491792e-08, 6.62430780e-08],
        ...,
        [3.06941867e-07, 3.95071425e-07, 5.01085468e-07, ...,
         3.13539116e-08, 2.69229022e-08, 2.29947006e-08],
        [1.98678789e-07, 2.55289694e-07, 3.23437915e-07, ...,
         2.51735561e-08, 2.16350683e-08, 1.84981599e-08],
        [1.27091576e-07, 1.62793330e-07, 2.05784816e-07, ...,
         2.01650032e-08, 1.73449704e-08, 1.48449666e-08]],

       [[1.78289457e-06, 2.63289793e-06, 3.84450599e-06, ...,
         7.84599366e-08, 6.56179156e-08, 5.48583384e-08],
        [2.30844025e-06, 3.41273294e-06, 4.98668007e-06, ...,
         9.40617840e-08, 7.86141902e-08, 6.56914002e-08],
        [2.94388583e-06, 

In [28]:
Ccmf=np.load("Ccmf.npy")
pyscf.tools.molden.from_mo(pymol, "Ccmf.molden", Ccmf)

range1 =[i for i in range(102, 108)] 
di = Ccmf[:,range1] @  Ccmf[:,range1].T
pyscf.tools.cubegen.density(pymol, 'fragden_virt.cube', di)

array([[[1.16268964e-06, 1.71160592e-06, 2.49421583e-06, ...,
         6.61510219e-08, 5.54565105e-08, 4.64481363e-08],
        [1.50289001e-06, 2.21592461e-06, 3.23269492e-06, ...,
         7.92870195e-08, 6.64326556e-08, 5.56190124e-08],
        [1.91402619e-06, 2.82574858e-06, 4.12592975e-06, ...,
         9.45084006e-08, 7.91491792e-08, 6.62430780e-08],
        ...,
        [3.06941867e-07, 3.95071425e-07, 5.01085468e-07, ...,
         3.13539116e-08, 2.69229022e-08, 2.29947006e-08],
        [1.98678789e-07, 2.55289694e-07, 3.23437915e-07, ...,
         2.51735561e-08, 2.16350683e-08, 1.84981599e-08],
        [1.27091576e-07, 1.62793330e-07, 2.05784816e-07, ...,
         2.01650032e-08, 1.73449704e-08, 1.48449666e-08]],

       [[1.78289457e-06, 2.63289793e-06, 3.84450599e-06, ...,
         7.84599366e-08, 6.56179156e-08, 5.48583384e-08],
        [2.30844025e-06, 3.41273294e-06, 4.98668007e-06, ...,
         9.40617840e-08, 7.86141902e-08, 6.56914002e-08],
        [2.94388583e-06, 